apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: counter-ds
spec:
    selector:
        matchLabels:
            app: counter
    template:
        metadata:
            name: counter-ds
            labels:
                app: counter
        spec:
            tolerations:
            - effect: NoSchedule
              operator: Exists
            containers:
            - name: counter
              image: "sabya10jan/counter:1.2"
              volumeMounts:
              - name: counter
                mountPath: /app/
            volumes:
            - name: counter
              persistentVolumeClaim:
                claimName: counter-daemonset
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: counter-daemonset
spec:
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 50Mi
    storageClassName: standard
