apiVersion: v1
kind: Pod
metadata:
    name: myapp-pod
    labels:
        app: myapp
spec:
    initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c', 'untill nslookup myservice; do echo waiting for myservice; sleep 20; done;']
    containers:
    - name: myapp-container
      image: busybox:1.28
      command: ['sh', '-c', 'echo The app is running!&& sleep 3600']
